version: "3"

services:
  node1:
    build: /
    hostname: node1
    tty: true
    networks:
      - default_network

  node2:
    build: /
    hostname: node2
    tty: true
    networks:
      - default_network

  node3:
    build: /
    hostname: node3
    tty: true
    networks:
      - default_network


  node4:
    build: /
    hostname: node4
    tty: true
    networks:
      - default_network

networks:
  default_network:
    driver: bridge