version: "3"

services:
  node1:
    build: miner
    tty: true
    networks:
      default_network:
        aliases:
          - node1

  node2:
    build: miner
    tty: true
    networks:
      default_network:
        aliases:
          - node2

  node3:
    build: miner
    tty: true
    networks:
      default_network:
        aliases:
          - node3


  simulator:
    build: ./simulator
    hostname: simulator
    container_name: simulator
    tty: true
    networks:
      default_network:
        aliases:
          - simulator
    depends_on:
      - node1
      - node2
      - node3

networks:
  default_network:
    driver: bridge